### ISSUE TITLE
Add instructions for melodic

### ISSUE THREAD

**Issue by tobi-v** [PilzDE/pilz_tutorials#11]
**Is your feature request related to a problem? Please describe.**
In step 4.2 of the [second tutorial](http://wiki.ros.org/pilz_robots/Tutorials/MoveRobotWithPilzCommand_planner), the instructions don't cover for ROS melodic. This could lead to unexpected behaviour for users who copy-paste the commands.

**Describe the solution you'd like**
Add a switch as in the other tutorials.

**Comment by agutenkunst** [comment]
Fixed.

**Comment by jschleicher** [comment]
Thanks!
