### ISSUE TITLE
Use GetCode/GetTaggedCode to easier synchronize GitHub and ROSWiki

### ISSUE THREAD

**Issue by SansoneG** [PilzDE/pilz_tutorials#13]
**Problem**
Changing source files in this repository or in their respective ROSWiki entries requires that work to be duplicated into their counterparts, which is errorprone at best and could be forgotten at worst.

**Solution**
Link the ROSWiki entries to this repository by using the Makro [GetCode/GetTaggedCode](http://library.isr.ist.utl.pt/docs/roswiki/WikiMacros.html#GetCode.2C_GetTaggedCode).
The remaining issue is that if the folder structure in this repository ever changes, this will require changes in ROSWiki aswell.

**Additional context**
This technique is also used in the official ROS Tutorials, e.g. [CPP-Tutorial](http://wiki.ros.org/roscpp_tutorials/Tutorials/WritingPublisherSubscriber#The_Code).
The tagged code for the above tutorial can be found [here](https://raw.githubusercontent.com/ros/ros_tutorials/kinetic-devel/roscpp_tutorials/talker/talker.cpp).

**Comment by agutenkunst** [comment]
Thanks for your Input. Applied it here http://wiki.ros.org/pilz_robots/Tutorials/HowToSetupTheRobot.
Rest will follow.

**Comment by ct2034** [comment]
We have one this in all tutorials now. Feel free to reopen if necessary
