### ISSUE TITLE
Notes on psen_scan_tutorials

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_tutorials#14]
1. **Creating a PSENscan application package**
   - [x] Is it really necessary to tell the user how to create a workspace and package. We can probably refer to general ros tutorials for this.
   - [x] Instead, I suggest an additional tutorial on hardware setup referencing https://www.pilz.com/download/open/PSEN_sc_M_Operat_Man_1005055-EN-02.pdf (p49)
      - [x] Connect power to blue and brown wires of `[1]`
      - [x] Connect PC via ethernet adapter cable to `[4]`
   - [x] Add a note, that it is required to set the host IP in the network adapter and then put it in the config
   - [x] We need to first set the scanner IP with the windows tool, right? What is the default value?
   - [x] What is the `evaluation device` mentioned in the manual (p69). Maybe we should mention in the tutorial that it is not needed with ROS, or is it?

2. **How to configure parameters with yaml**
   - [x] The rviz config is not installed (https://github.com/PilzDE/psen_scan/issues/25)
   - [x] We need more descriptive names than calling every config file `config.yaml` or `config.rviz`
   - [x] We can probably use `How to configure parameters with yaml` to explain the necessary parameters quickly (bare minimum setup)
   - [x] This should include a rviz screenshot showing the desired final state. Maybe we can do it as a gif to make it a little more lively.

3. **Launching multiple scanners**
   - [x] The manual recommends (p21) to connect multiple scanners in series. Why does http://wiki.ros.org/psen_scan/Tutorials/LaunchingMultipleScanners use a switch?
   - [x] We need more descriptive names than calling every config file `config` or `config2`
   - [x] Would this be optional or advanced? Assuming most customers buy one scanner first.

**Comment by SansoneG** [comment]
>    * [ ]  Instead, I suggest an additional tutorial on hardware setup referencing https://www.pilz.com/download/open/PSEN_sc_M_Operat_Man_1005055-EN-02.pdf (p49)
>      
>      * Connect power to blue and brown wires of `[1]`
>      * Connect PC via ethernet adapter cable to `[4]`

Sounds very good to me.

>    * [ ]  Add a note, that it is required to set the host IP in the network adapter and then put it in the config

Should we also add this to the Readme?

>    * [ ]  What is the `evaluation device` mentioned in the manual (p69). Maybe we should mention in the tutorial that it is not needed with ROS, or is it?

The evaluation device can for example be a PNOZmulti or PSS4000 as mentioned on p69/70.

>    * [ ]  We can probably use `How to configure parameters with yaml` to explain the necessary parameters quickly (bare minimum setup)

Do you mean something like the [ROS API](https://github.com/PilzDE/psen_scan/blob/melodic-devel/README.md#ros-api)?

>    * [ ]  The manual recommends (p21) to connect multiple scanners in series. Why does http://wiki.ros.org/psen_scan/Tutorials/LaunchingMultipleScanners use a switch?

It is only possible connect slave devices in series with a master device. Our ROS package currently only supports master devices.

>    * [ ]  Would this be optional or advanced? Assuming most customers buy one scanner first.

In my opinion it is common enough to buy at least two scanners for an application (for the 360° view).
