### ISSUE TITLE
Notes of a tutorial workthrough

### ISSUE THREAD

**Issue by rfeistenauer** [PilzDE/pilz_tutorials#16]
Some notes form the workthough of http://wiki.ros.org/psen_scan/Tutorials/SettingUpPSENscanHW:
- [x] description of PilzDe/pilz_tutorials needs to be updated
- [x] Introduction 
  - [x] replace "using our Windows ..." with "using the Pilz configuration tool"
- [x] Prerequisites: 
  - [x] When restrict the configurator to 3.0.0, which scanner versions work with that configurator.
  - [x] Manuel is inked to PsenScan sc M 3/5 are those the only supported onse?
  - [x] State exactly which scanner versions are supported (to be consistent with manual an shop)
  - [x] The Ethernet Cable/power cable is it shipped with the scanner or can we add a link to the shop?
  - [x] State the required operation system 
  - [x] "An Ethernet interface to communicate from your PC via Ethernet to the PSENscan laser scanner." simplify e.g. "PC with Ethernet"
  - [x] installation tutorial (after point "A 24V DC power supply. ") could be a separate section
  - [x] image showing the psen scan bottom with the connection probably has the ethernet on the wrong adapter and the power slot is not clearly identifiable
  - [x] second image PSENscan_sample_setup.png is only supposed to show ethernet has to be connected to the psenscan? 
- [x] Don't see the benefit of this image.
- [x] 3.0
  - [x] Is this Note really necessary? The scanner is also found from another subnet and the ip can be changed still.
- [x] 3.1
  - [x] the configurator is already a prerequisite, does it need another section?
- [x] 3.2 
  - [x] "Device → Search device" is actually "Scanner -> Search device"
- [x] 3.3
  - [x] Why change the Ip Address?
  - [x] no admin pw is required to change the ip
  - [x] being in another subnet opens this ip change window on double click
  - [x] "...connecting to the network and click OK." and "Click OK to continue" is one OK to much
- [x] 3.4
  - [x] "Click on new configuration. " its "Create new configuration"
  - [x] maybe add a note on where to find the scanner version on the product
  - [x] "n the general **properties** " 
  - [x] "the right number of pins for your connection" which connection? Ethernet?
  - [x] "Click at next and choose your scanner. " => "Click next ... "
  - [x] the "Device not available warning " should not be here. For one we did already fix the ip in previous section and if this doesn't happen often it should be in troubleshooting anyway.
  - [x] "During download the PSENscan laser scanner screen becomes black. " Its first black, then it shows a File with the text DL DNC below.
  - [x] "The finish dialog appears, the PSENscan laser scanner screen comes back to life." It was "back to life" until i clicked "accept" and went black again during the Finish process.
  - [x] "to switch to the Monitoring tab. In this tab an image of the ..." => "to display the 2d surroundings of the scanner."

**Comment by rfeistenauer** [comment]
Notes to http://wiki.ros.org/psen_scan/Tutorials/ConfiguringPsenScanParametersWithYaml

* Note: This tutorial assumes ... link is connected to wrong tutorial

**Comment by martiniil** [comment]
Notes for http://wiki.ros.org/psen_scan/Tutorials/ConfiguringPsenScanParametersWithYaml:

* Link to previous tutorial is wrongly set
* Page name and description are inconsistent with title of tutorial
* 1 Introduction:
  * Strange sentences. Suggestion: "This tutorial teaches you to set up and launch a ROS driver for the PSENscan laser scanner. This includes creating a new ROS package to read and display laser scanner data."
* 3 Required parameters
  * "the following mandatory parameters are required" -> "the following parameters are required" or "the following parameters are mandatory"
  * "ROS driver for the PSENscan laser scanner", we think "for the PSENscan laser scanner" can be omitted from here on.
  * It would make more sense to create the package first and then describe the parameters
* 4 Create a ROS package:
  * `catkin_create_pkg` command needs the `--rosdistro` argument!
  * Do we need the copyright/license header in the yaml-file/launch-file?
  * Why do the yaml/launch-file include tags? (e.g. `%Tag(FULLTEXT)%`)
  * It should be mentioned that the user has to change the ip addresses accordingly (The previous tutorial showed how these could be altered)
* 6 Conclusion:
  * Should we mention further steps?
  * Suggestion for the text: "In this tutorial you created a basis for an application using the PSENscan laser scanner."

**Comment by martiniil** [comment]
Notes for http://wiki.ros.org/psen_scan/Tutorials/LaunchingMultipleScanners:
* 3 Creating the config files:
  * "Here´s an example" -> "Here is an example"
* 4 Creating the launch file:
  * What is the use of the tags in the launch-file?
  * Add a sentence at the end about what is different to the previous launch-file.
* 5 Start the application:
  * In order to show the data of both scanners simultaneously, the location of each scanner should be defined in a given environment (define base links in urdf-file like in the pilz_robots tutorials).
