### ISSUE TITLE
Cannot apt-install ros-noetic-pilz-industrial-motion

### ISSUE THREAD

**Issue by gy2256** [PilzDE/pilz_tutorials#27]
Hello, 

I try to follow the tutorial from https://wiki.ros.org/pilz_robots/Tutorials/MoveRobotWithPilzCommand_planner#Install_Pilz_industrial_motion_package. 

I have Ubuntu 20.04 with ROS noetic. When I run the `sudo apt install ros-noetic-pilz-industrial-motion`, the terminal shows 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-noetic-pilz-industrial-motion
```

**Comment by jschleicher** [comment]
Probably a temporary issue or misconfiguration. Please re-open, if the problem persists.
