### ISSUE TITLE
my_application.launch file can't be executed

### ISSUE THREAD

**Issue by zeldamax** [PilzDE/pilz_tutorials#34]
### Commit
Latest (6868eb37e6ce278b5b863360b6c00657eedd5113)

### Steps to reproduce
How can the issue/bug be reproduced?
1. Complete first tutorial (http://wiki.ros.org/pilz_robots/Tutorials/ModelYourApplicationWithPRBT)
2. Complete second tutorial (http://wiki.ros.org/pilz_robots/Tutorials/MoveRobotWithPilzCommand_planner)
3. Try to use the launch file: `roslaunch pilz_tutorial my_application.launch`

### Expected behavior
I think the launch file should be executed, RViz should show up and I should be able to use the pilz path planner using RViz or Python.

### Observed behavior
The launch file / the package can't be found. The following error appears in terminal:
```
RLException: [my_application.launch] is neither a launch file in package [pilz_tutorial] nor is [pilz_tutorial] a launch file name
```

RViz doesn't open up. The package can't even be found using `rospack find pilz_tutorial` or `roscd pilz_tutorial`.

### My attempts at solving the issue
I have tried to find a solution by looking for other people who had a similiar issue. In most cases, people solved this problem of not finding the launch file by sourcing the setup.bash file by executing the following command:
` ~/catkin_ws/devel/setup.bash`
and then trying to use the launch file again. I did exactly this, but it doesn't seem to work. I even added the line to the ~/.bashrc file, so that it gets executed every time I open a new terminal window, but it still doesn't find it.

Perhaps using `catkin_make` or `catkin build` makes a difference?

Hopefully you know the solution to the problem or maybe you can give me a hint. Thank you very much in advance!

**Comment by mappold** [comment]
Never mind, I found the mistake. The CMakeLists.txt file inside the directory `~/catkin_ws/src/pilz_tutorial` was gone. I recreated the package using `catkin_create_pkg pilz_tutorial prbt_moveit_config` and sourced the setup file again using `source ~/catkin_ws/devel/setup.bash` and it works now! Sorry for bothering you.
