### ISSUE TITLE
Remove preceding line numbers and dollar signs

### ISSUE THREAD

**Issue by tobi-v** [PilzDE/pilz_tutorials#9]
**Is your feature request related to a problem? Please describe.**
If you want to copy-paste the code examples, you need to remove the preceding symbols in each line by hand.

**Describe the solution you'd like**
Lines without preceding symbols or line numbers.

**Comment by ct2034** [comment]
At least for line numbers, there is a button:
![Screenshot from 2020-04-23 10-37-13](https://user-images.githubusercontent.com/6976069/80078148-cbb80700-854e-11ea-8f33-87274e3f89b7.png)
